Fix compiler error in Visual Studio 2015
There is a compiler error C2398: "conversion from 'std::chrono::system_clock::rep' to 'unsigned int' requires a narrowing conversion" in Visual Studio 2015. The change solves this problem. The reason is in the way of variable initialization.